
// [파일 역할]: 템플릿 팔렛 가중치(Weight) 계산 인터페이스 및 RocksDB 기준 가중치 정보
// [주요 기능]: `do_something`, `cause_error` 디스패처 호출에 대한 CPU 실행 시간 및 DB Read/Write 가중치 산출

//! Autogenerated weights for pallet_template
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

// [트레이트 정의]: 템플릿 팔렛의 디스패처 호출에 필요한 가중치 계산 규격
pub trait WeightInfo {
	/// `do_something` 호출에 대한 가중치 계산
	fn do_something() -> Weight;
	/// `cause_error` 호출에 대한 가중치 계산
	fn cause_error() -> Weight;
}

// [목적 / 효과]: Substrate 노드 및 권장 하드웨어 환경 기준 실제 가중치 구현체
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// 스토리지: Template Something (r:0 w:1)
	fn do_something() -> Weight {
		// 최소 실행 시간: 8,000,000 피코초 + 스토리지 1회 쓰기(Write) 가중치 합산
		Weight::from_parts(9_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// 스토리지: Template Something (r:1 w:1)
	fn cause_error() -> Weight {
		// 최소 실행 시간: 6,000,000 피코초 + 스토리지 1회 읽기(Read) 및 1회 쓰기(Write) 가중치 합산
		Weight::from_parts(6_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// [하위 호환성 및 테스트용 더미 구현체]: 기본 RocksDbWeight 기반 고정 가중치
impl WeightInfo for () {
	/// Storage: Template Something (r:0 w:1)
	fn do_something() -> Weight {
		Weight::from_parts(9_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Template Something (r:1 w:1)
	fn cause_error() -> Weight {
		Weight::from_parts(6_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}

